#' loadcodontable
#'
#' Loads a codon table as a dataframe.
#'
#' @export
#' @examples
#' codon_table <- loadcodontable()

loadcodontable <- function(){

  codon_table <- data.frame(
    amino_acid_3 = c(rep("Ala", 4),
                     rep("Arg", 6),
                     rep("Asn", 2),
                     rep("Asp", 2),
                     rep("Cys", 2),
                     rep("Gln", 2),
                     rep("Glu", 2),
                     rep("Gly", 4),
                     rep("His", 2),
                     rep("Ile", 3),
                     rep("Leu", 6),
                     rep("Lys", 2),
                     rep("Met", 1),
                     rep("Phe", 2),
                     rep("Pro", 4),
                     rep("Ser", 6),
                     rep("Thr", 4),
                     rep("Trp", 1),
                     rep("Tyr", 2),
                     rep("Val", 4),
                     rep("STOP", 3)
    ),
    amino_acid_1 = c(rep("A", 4),
                     rep("R", 6),
                     rep("N", 2),
                     rep("D", 2),
                     rep("C", 2),
                     rep("Q", 2),
                     rep("E", 2),
                     rep("G", 4),
                     rep("H", 2),
                     rep("I", 3),
                     rep("L", 6),
                     rep("K", 2),
                     rep("M", 1),
                     rep("F", 2),
                     rep("P", 4),
                     rep("S", 6),
                     rep("T", 4),
                     rep("W", 1),
                     rep("Y", 2),
                     rep("V", 4),
                     rep("*", 3)
    ),
    group = c(rep("small", 4),
              rep("basic", 6),
              rep("amide", 2),
              rep("acidic", 2),
              rep("nucleophilic", 2),
              rep("amide", 2),
              rep("acidic", 2),
              rep("small", 4),
              rep("basic", 2),
              rep("hydrophobic", 3),
              rep("hydrophobic", 6),
              rep("basic", 2),
              rep("hydrophobic", 1),
              rep("aromatic", 2),
              rep("hydrophobic", 4),
              rep("nucleophilic", 6),
              rep("nucleophilic", 4),
              rep("aromatic", 1),
              rep("aromatic", 2),
              rep("hydrophobic", 4),
              rep("stop", 3)
    ),
    codons = c("GCT", "GCC", "GCA", "GCG",
               "CGT", "CGC", "CGA", "CGG", "AGA", "AGG",
               "AAT", "AAC",
               "GAT", "GAC",
               "TGT", "TGC",
               "CAA", "CAG",
               "GAA", "GAG",
               "GGT", "GGC", "GGA", "GGG",
               "CAT", "CAC",
               "ATT", "ATC", "ATA",
               "TTA", "TTG", "CTT", "CTC", "CTA", "CTG",
               "AAA", "AAG",
               "ATG",
               "TTT", "TTC",
               "CCT", "CCC", "CCA", "CCG",
               "TCT", "TCC", "TCA", "TCG", "AGT", "AGC",
               "ACT", "ACC", "ACA", "ACG",
               "TGG",
               "TAT", "TAC",
               "GTT", "GTC", "GTA", "GTG",
               "TAA", "TAG", "TGA"
    ),
    compressed = c(rep("GCN", 4),
                   rep("CGN/AGR", 6),
                   rep("AAY", 2),
                   rep("GAY", 2),
                   rep("TGY", 2),
                   rep("CAR", 2),
                   rep("GAR", 2),
                   rep("GGN", 4),
                   rep("CAY", 2),
                   rep("ATH", 3),
                   rep("YTR/CTN", 6),
                   rep("AAR", 2),
                   rep("ATG", 1),
                   rep("TTY", 2),
                   rep("CCN", 4),
                   rep("TCN/AGY", 6),
                   rep("ACN", 4),
                   rep("TGG", 1),
                   rep("TAY", 2),
                   rep("GTN", 4),
                   rep("TAR/TRA", 3)
    )
  )

  return(codon_table)
}
